### ISSUE TITLE
Please update to Gnucash 3.6

### ISSUE THREAD

**Issue by ngiger** [Gnucash/gnucash-on-flatpak#1]
Thanks for your work. I wanted to test the new Gnucash 3.6 but found that you pack still 3.2. 
It would be nice if you had time to update it.
Thanks in advance

**Comment by jralls** [comment]
What are you talking about? This repo for building a flatpak with any GnuCash version you like.

**Comment by fellen** [comment]
Following [IRC](https://lists.gnucash.org/logs/2019/07/09.html#T11:44:10) I assume tho OP is talking about [Flathub's Repo](https://flathub.org/apps/details/org.gnucash.GnuCash).

@ngiger, you can download our builds from https://code.gnucash.org/builds/flatpak/.
So, can we close this issue?

**Comment by ngiger** [comment]
Okay. I managed to install gnucash 3.6 from the link given above using the following commands:

    wget https://code.gnucash.org/builds/flatpak/gnucash-flatpak.gpg
    flatpak remote-add --gpg-import=gnucash-flatpak.gpg gnucash https://code.gnucash.org/builds/flatpak/repo
    flatpak install gnucash org.gnucash.GnuCash # selecting option 28 of 108
 
My problem stemmed from the fact that I tried to follow the instructions under https://flathub.org/apps/details/org.gnucash.GnuCash. Is there any possibility that you update this link or the link given in the gnucash wiki https://wiki.ubuntuusers.de/GnuCash/#ber-Flatpak

**Comment by fellen** [comment]
@jralls I think we should add this tested installation instructions to our README.md as section "Installing Nightlies"

@ngiger AFAIK none of us GnuCash core devs is a member of flathub.org or ubuntuusers.de. You should ask somebody already involved there.

**Comment by jralls** [comment]
@fellen, Derek has asked that we not publicize the flatpak build until he finishes his house remodel and moves back in. His bandwidth is quite limited until then. Discuss further on IRC.
